name: Build TWRP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Sync TWRP Minimal
      run: |
        mkdir TWRP && cd TWRP &&
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1 &&
        repo sync -j$(nproc --all)

    - name: Clone TWRP Tree
      run: git clone https://github.com/nokidevz/twrp_device_xiaomi_viva.git device/xiaomi/viva

    - name: Build TWRP
      run: |
        source build/envsetup.sh &&
        lunch twrp_viva-eng &&
        mka bootimage -j$(nproc --all)
   
    - name: Upload build
      uses: actions/upload-artifact@v3.1.1
      with:
        name: twrp.zip
        path: $OUT/boot.img
