name: Build TWRP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create directory and navigate
      run: |
        mkdir twrp && cd twrp
        pwd
